### ISSUE TITLE
Can't upload to S3

### ISSUE THREAD

**Issue by Stajor** [mrrooijen/mongoid-paperclip#51]
After uploading file I get 200 status. New one row created in DB, but only with _id field
No files uploaded to S3

What am I doing wrong?

Gemfile

```
gem 'rails', '4.0.3'
gem 'mongoid', '~> 4.0.0.beta1', github: 'mongoid/mongoid'
gem 'mongoid-paperclip', :require => 'mongoid_paperclip', :github => 'meskyanichi/mongoid-paperclip', :branch => 'master'
gem 'aws-sdk', '~> 1.34.1'
```

Model

```
class Draft
  include Mongoid::Document
  include Mongoid::Paperclip

  has_mongoid_attached_file :draft,
    :path => ':attachment/:id/:style.:extension',
    :storage        => :s3,
    :s3_credentials => File.join(Rails.root, 'config', 'aws.yml'),
    :styles => {
      :small   => ['298x160#', :png]
    }
end
```

aws.yml

```
development:
  bucket: site-develop
  access_key_id: MYKEY
  secret_access_key: MYSECRETKEY
  s3_host_name: s3-eu-west-1.amazonaws.com
```
